initial push for dashboard get and import
Expedient/ansible-collection-elastic pull request #38
Opened 2022-08-04 18:27 UTC by ianrscottexp

New Features:
- Get Dashboard Information
- Import Dashboard
- Export Dashboard

2022-08-04 19:44 UTC, mgaruccio requested changes
Have a few notes on small updates, but also need to make sure that the pipfile and requirements files get updated so we can apply to tower.

2022-08-04 19:46 UTC, ianrscottexp commented on galaxy.yml
> +version: 2.3.2
Version is currently 2.3.1.  I should of rebased before I started to code

2022-08-04 19:49 UTC, ianrscottexp commented on plugins/module_utils/kibana.py
> +    import requests
I have moved the imports

2022-08-04 19:52 UTC, mgaruccio reviewed
lgtm

2022-08-04 19:52 UTC, mgaruccio approved these changes

2022-08-08 18:30 UTC, exp-hc approved these changes
LGTM

2022-08-08 18:40 UTC, merged